# Generated by Django 3.1.7 on 2021-11-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Res2004',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aaaa', models.CharField(blank=True, max_length=4, null=True)),
                ('codcta', models.CharField(blank=True, max_length=20, null=True)),
                ('debe00', models.FloatField(default=0)),
                ('haber00', models.FloatField(default=0)),
                ('debe01', models.FloatField(default=0)),
                ('haber01', models.FloatField(default=0)),
                ('debe02', models.FloatField(default=0)),
                ('haber02', models.FloatField(default=0)),
                ('debe03', models.FloatField(default=0)),
                ('haber03', models.FloatField(default=0)),
                ('debe04', models.FloatField(default=0)),
                ('haber04', models.FloatField(default=0)),
                ('debe05', models.FloatField(default=0)),
                ('haber05', models.FloatField(default=0)),
                ('debe06', models.FloatField(default=0)),
                ('haber06', models.FloatField(default=0)),
                ('debe07', models.FloatField(default=0)),
                ('haber07', models.FloatField(default=0)),
                ('debe08', models.FloatField(default=0)),
                ('haber08', models.FloatField(default=0)),
                ('debe09', models.FloatField(default=0)),
                ('haber09', models.FloatField(default=0)),
                ('debe10', models.FloatField(default=0)),
                ('haber10', models.FloatField(default=0)),
                ('debe11', models.FloatField(default=0)),
                ('haber11', models.FloatField(default=0)),
                ('debe12', models.FloatField(default=0)),
                ('haber12', models.FloatField(default=0)),
                ('debe13', models.FloatField(default=0)),
                ('haber13', models.FloatField(default=0)),
            ],
        ),
    ]
