# Generated by Django 3.2.8 on 2021-10-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecasi', models.DateField(blank=True, null=True)),
                ('lib', models.CharField(blank=True, max_length=20, null=True)),
                ('nroasi', models.IntegerField()),
                ('nrodoc', models.CharField(blank=True, max_length=20, null=True)),
                ('codcta', models.CharField(blank=True, max_length=20, null=True)),
                ('monmn', models.FloatField()),
            ],
        ),
    ]
